includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-semi.yaml

variables:
  binary_name: skate
  description: "A personal key value store 🛼"
  github_url: "https://github.com/charmbracelet/skate"
  maintainer: "Ayman Bagabas <ayman@charm.sh>"
  brew_commit_author_name: "Ayman Bagabas"
  brew_commit_author_email: "ayman@charm.sh"
