project_name: skate

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: "skate"
    binary: "skate"
    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      # - freebsd
      # - openbsd
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

dockers:
  - image_templates:
      - charmcli/skate:latest-amd64
      - charmcli/skate:{{ .Tag }}-amd64
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/charmbracelet/skate:latest-amd64
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-amd64
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-amd64
    ids: [skate]
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx
  - image_templates:
      - charmcli/skate:latest-arm64
      - charmcli/skate:{{ .Tag }}-arm64
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/charmbracelet/skate:latest-arm64
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-arm64
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-arm64
    ids: [skate]
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx
  - image_templates:
      - charmcli/skate:latest-armv7
      - charmcli/skate:{{ .Tag }}-armv7
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-armv7
      - ghcr.io/charmbracelet/skate:latest-armv7
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-armv7
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-armv7
    ids: [skate]
    goarch: arm
    goarm: 7
    build_flag_templates:
      - --platform=linux/arm32/v7
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.source=https://github.com/charmbracelet/skate
      - --label=org.opencontainers.image.version={{ .Tag }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - name_template: charmcli/skate:{{ .Tag }}
    image_templates:
      - charmcli/skate:{{ .Tag }}-amd64
      - charmcli/skate:{{ .Tag }}-arm64
      - charmcli/skate:{{ .Tag }}-armv7
  - name_template: ghcr.io/charmbracelet/skate:{{ .Tag }}
    image_templates:
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-amd64
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-arm64
      - ghcr.io/charmbracelet/skate:{{ .Tag }}-armv7
  - name_template: charmcli/skate:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-amd64
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-arm64
      - charmcli/skate:v{{ .Major }}.{{ .Minor }}-armv7
  - name_template: ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/charmbracelet/skate:v{{ .Major }}.{{ .Minor }}-armv7
  - name_template: charmcli/skate:latest
    image_templates:
      - charmcli/skate:latest-amd64
      - charmcli/skate:latest-arm64
      - charmcli/skate:latest-armv7
  - name_template: ghcr.io/charmbracelet/skate:latest
    image_templates:
      - ghcr.io/charmbracelet/skate:latest-amd64
      - ghcr.io/charmbracelet/skate:latest-arm64
      - ghcr.io/charmbracelet/skate:latest-armv7

archives:
  - id: default
    builds:
      - skate
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  - builds:
      - skate

    vendor: charmbracelet
    homepage: "https://charm.sh/"
    maintainer: "Christian Rocha <christian@charm.sh>"
    description: "A personal key value store"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: 6
    tap:
      owner: charmbracelet
      name: homebrew-tap
    commit_author:
      name: "Christian Rocha"
      email: "christian@charm.sh"
    homepage: "https://charm.sh/"
    description: "A personal key value store"

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
